### ISSUE TITLE
multi_fast5_subset doesn't recognise the number of threads

### ISSUE THREAD

**Issue by mattloose** [nanoporetech/ont_fast5_api#16]
Running fas5_subset generate the following error:

fast5_subset -i #####/ -s #######_TargetReads/ -l ######_read_ids.txt --threads 1
Traceback (most recent call last):                                                                                                                                               |  0% ETA:  --:--:--
 File “/usr/local/bin/fast5_subset”, line 10, in <module>
   sys.exit(main())
 File “/usr/local/lib/python3.5/dist-packages/ont_fast5_api/conversion_tools/multi_fast5_subset.py”, line 289, in main
   mulitfilter.run_batch()
 File “/usr/local/lib/python3.5/dist-packages/ont_fast5_api/conversion_tools/multi_fast5_subset.py”, line 96, in run_batch
   with Pool(self.num_workers) as pool:
 File “/usr/lib/python3.5/multiprocessing/context.py”, line 118, in Pool
   context=self.get_context())
 File “/usr/lib/python3.5/multiprocessing/pool.py”, line 161, in __init__
   raise ValueError(“Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

**Comment by mattloose** [comment]
Ah - it would appear that adding the --recursive flag will get past this bug, but then you uncover another one...

/ 0 of 363|                                                                                                                                                                     |N/A% ETA:  --:--:--Traceback (most recent call last):
  File "/usr/local/bin/fast5_subset", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/ont_fast5_api/conversion_tools/multi_fast5_subset.py", line 289, in main
    mulitfilter.run_batch()
  File "/usr/local/lib/python3.5/dist-packages/ont_fast5_api/conversion_tools/multi_fast5_subset.py", line 94, in run_batch
    self._launch_sync_tasks()
  File "/usr/local/lib/python3.5/dist-packages/ont_fast5_api/conversion_tools/multi_fast5_subset.py", line 121, in _launch_sync_tasks
    self._update_file_lists(reads=reads, out_file=out_file, in_file=in_file)
  File "/usr/local/lib/python3.5/dist-packages/ont_fast5_api/conversion_tools/multi_fast5_subset.py", line 173, in _update_file_lists
    self.pbar.update(self.pbar.currval + len(reads) + in_file_exhausted)
AttributeError: 'ProgressBar' object has no attribute 'currval'
| 363 of 363|###################################################################################################################################################################|100% Time:  0:00:00

**Comment by mattloose** [comment]
I can temporarily fix by just commenting out line 173!

**Comment by fbrennen** [comment]
Hi @mattloose -- thanks for letting us know. The `currval` error usually shows up when you don't have the correct `progressbar` package installed -- see here: https://github.com/nanoporetech/ont_fast5_api/issues/9

**Comment by mattloose** [comment]
Ta.

**Comment by DelphIONe** [comment]
I have the same problem with command 
 fast5_subset --input fast5/ --save_path fast5_reads4/ --read_id_list liste_ont.txt 
Traceback (most recent call last):                                                                                                                                                                                                                |  0% ETA:  --:--:--
  File "/usr/local/bin/fast5_subset", line 9, in <module>
    load_entry_point('ont-fast5-api==1.4.4', 'console_scripts', 'fast5_subset')()
  File "/usr/local/lib/python2.7/dist-packages/ont_fast5_api-1.4.4-py2.7.egg/ont_fast5_api/conversion_tools/multi_fast5_subset.py", line 290, in main
    mulitfilter.run_batch()
  File "/usr/local/lib/python2.7/dist-packages/ont_fast5_api-1.4.4-py2.7.egg/ont_fast5_api/conversion_tools/multi_fast5_subset.py", line 97, in run_batch
    with Pool(self.num_workers) as pool:
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 152, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

I have tried with recursive option but the error is the same.

Thanks for your help,

**Comment by DelphIONe** [comment]
With -n 4 it's ok! (I have only 4 interest reads)
