### ISSUE TITLE
[bug report] single_to_multi_fast5 fail

### ISSUE THREAD

**Issue by yipukangda** [nanoporetech/ont_fast5_api#27]
intending to split a fast5 to multiple one with command 
```
single_to_multi_fast5 -i ./fast5_pass -s ./fast5_split --filename_base genome_seq
```
get following error massage:

```
RROR:ont_fast5_api.conversion_tools.single_to_multi_fast5:'<' not supported between instances of 'str' and 'float'
	Failed to add single read file: './fast5_pass/FAH73916_82e3313796fbbb21fb94d631bf768f22f72b733c_0.fast5' to './fast5_split/genome_seq_0.fast5'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/qitan/anaconda/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/qitan/anaconda/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/qitan/anaconda/lib/python3.7/multiprocessing/pool.py", line 486, in _handle_results
    cache[job]._set(i, obj)
  File "/home/qitan/anaconda/lib/python3.7/multiprocessing/pool.py", line 662, in _set
    self._callback(self._value)
  File "/home/qitan/anaconda/lib/python3.7/site-packages/ont_fast5_api/conversion_tools/single_to_multi_fast5.py", line 28, in update
    pbar.update(pbar.currval + 1)
AttributeError: 'ProgressBar' object has no attribute 'currval'
```

**Comment by fbrennen** [comment]
Ah, out of curiosity, how did you install `ont_fast5_api`? Did you get it from pip / pypi?

**Comment by wdecoster** [comment]
If you want to split a multi-read file to single read files you should use `multi_to_single_fast5`, and not `single_to_multi_fast5`

**Comment by yipukangda** [comment]
@wdecoster Thanks so much, I misunderstood the mean of `multi_to_single_fast5`
