### ISSUE TITLE
filename_mapping.txt gets overwritten

### ISSUE THREAD

**Issue by mbhall88** [nanoporetech/ont_fast5_api#8]
Thanks for the conversion tools!

When using `multi_to_single_fast5` the resulting `filename_mapping.txt` file only seems to contain the mappings for one multi-fast5 file, rather than all of them. i.e it only has 4000 lines regardless of the number of multi-fast5s I run the tool on.

I believe this is due to the way the file is being opened here https://github.com/nanoporetech/ont_fast5_api/blob/482604506c3fc1661163fd02b02a7131f67b8878/ont_fast5_api/conversion_tools/multi_to_single_fast5.py#L37
as it opens the file for writing, which will overwrite the file if it already exists.  

Maybe a better solution would be to hold the mappings in a `dict` and then write this file at the end? Or open the file in append mode `'a'`, however, I guess this might get tricky if multiple threads try to write to the file at the same time?

**Comment by hygine** [comment]
Traceback (most recent call last):
  File "/share/nas2/genome/biosoft/Python/3.4.3/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/share/nas2/genome/biosoft/Python/3.4.3/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/share/nas2/genome/biosoft/Python/3.4.3/lib/python3.4/multiprocessing/pool.py", line 436, in _handle_results
    cache[job]._set(i, obj)
  File "/share/nas2/genome/biosoft/Python/3.4.3/lib/python3.4/multiprocessing/pool.py", line 604, in _set
    self._callback(self._value)
  File "/share/nas2/genome/biosoft/Python/3.4.3/lib/python3.4/site-packages/ont_fast5_api-1.2.0-py3.4.egg/ont_fast5_api/conversion_tools/multi_to_single_fast5.py", line 40, in update
    pbar.update(pbar.currval + 1)
AttributeError: 'ProgressBar' object has no attribute 'currval'

how this error ? may be connect with this.

**Comment by fbrennen** [comment]
Hi @mbhall88 -- good catch! We'll get this fixed ASAP.

**Comment by fbrennen** [comment]
Hi @mbhall88 -- we've just pushed 1.3.0 with a fix for this. Can you try it out and see if it does what you expect?

**Comment by mbhall88** [comment]
Tested and working as expected @fbrennen . Thanks for the speedy fix.
