### ISSUE TITLE
AttributeError: 'ProgressBar' object has no attribute 'currval'

### ISSUE THREAD

**Issue by hygine** [nanoporetech/ont_fast5_api#9]
Traceback (most recent call last):
  File "/share/nas2/genome/biosoft/Python/3.4.3/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/share/nas2/genome/biosoft/Python/3.4.3/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/share/nas2/genome/biosoft/Python/3.4.3/lib/python3.4/multiprocessing/pool.py", line 436, in _handle_results
    cache[job]._set(i, obj)
  File "/share/nas2/genome/biosoft/Python/3.4.3/lib/python3.4/multiprocessing/pool.py", line 604, in _set
    self._callback(self._value)
  File "/share/nas2/genome/biosoft/Python/3.4.3/lib/python3.4/site-packages/ont_fast5_api-1.2.0-py3.4.egg/ont_fast5_api/conversion_tools/multi_to_single_fast5.py", line 40, in update
    pbar.update(pbar.currval + 1)
AttributeError: 'ProgressBar' object has no attribute 'currval'

**Comment by hygine** [comment]
@fbrennen

**Comment by fbrennen** [comment]
Hi @hygine -- I've tried to replicate this without success. How did you install the package? Did you use pip? Have you tried installing ont-fast5-api within a virtual environment to see if that works? 

It would also help to know what version of `progressbar` you're using:

`pip freeze | grep progressbar` or `python -c 'import progressbar; print(progressbar.__version__)'`

**Comment by hygine** [comment]
Hi @fbrennen  The version of `progressbar` I'm using:
progressbar2             3.38.0    
progressbar33            2.4

**Comment by fbrennen** [comment]
Ok, great -- that's not the correct package (it should be progressbar33, not progressbar2). Can you uninstall that one?

**Comment by hygine** [comment]
OK，thank you ,i will reinstall it.

**Comment by fbrennen** [comment]
Hi @hygine -- is everything working now?

**Comment by hygine** [comment]
when I reinstall it looks fine, thank you. @fbrennen
